function Hd = test_filter_1
%TEST_FILTER_1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 09-Nov-2017 17:58:22

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 80000;  % Sampling Frequency

Fstop1 = 2000;            % First Stopband Frequency
Fpass1 = 4000;            % First Passband Frequency
Fpass2 = 12000;           % Second Passband Frequency
Fstop2 = 14000;           % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
